Sentry
kodemia/api.kodemia.mx pull request #27
Opened 2021-03-01 19:27 UTC by arianaomi

2021-03-02 21:40 UTC, rrortegaa approved these changes

2021-03-03 09:03 UTC, devCharles requested changes

2021-03-03 09:03 UTC, devCharles commented on src/middlewares/sentry/tracingMiddleWare.js
> +}
Que hace este archivo? que son las transacciones? 🤔

2021-04-13 19:35 UTC, arianaomi commented on src/middlewares/sentry/tracingMiddleWare.js
> +}
Es para supervisar el rendimiento, se necesita configurar una transacción para que le de seguimiento.
https://docs.sentry.io/platforms/node/guides/koa/

2021-06-01 07:23 UTC, devCharles commented
@arianaomi puedes agregar las variables de entorno necesarias en vercel porfa? para darle approve a este y poder pasarlo a producción

2021-08-24 05:16 UTC, devCharles approved these changes

2021-08-24 05:18 UTC, merged