Docu sign
kodemia/api.kodemia.mx pull request #37
Opened 2021-06-28 16:36 UTC by arianaomi

- ADD DocuSign to send a file to be signed

2021-06-28 17:57 UTC, devCharles requested changes

2021-06-28 17:57 UTC, devCharles commented on src/routes/admissions.js
> +router.post('/calculator', async ctx => {
Pensandolo bien creo que quedaría mejor `/admissions/offer` por que este endpoint solo generara cartas ofertas

2021-06-28 17:57 UTC, devCharles commented on src/lib/docusign.js
> +async function worker (signerEmail, signerName) {
Por qué se llama worker esta función?

2021-06-28 17:57 UTC, devCharles commented on src/lib/docusign.js
> +  let env = new docusign.EnvelopeDefinition()
Podemos renombrar `env` por `envelop` porfa? para ser mas explícitos y evitar confusiones con environment

2021-06-28 17:57 UTC, devCharles commented on src/lib/docusign.js
> +function makeEnvelope (args) {
porque recibe args en lugar de los argumentos por separado? 👀

2021-06-28 18:28 UTC, rrortegaa approved these changes

2021-07-07 16:10 UTC, devCharles requested changes

2021-07-07 16:10 UTC, devCharles commented on src/lib/utils.js
> +}
Asi te evitas la logica extra
```suggestion
function formatCurrency (value) {
  const formatter = new Intl.NumberFormat('es-MX', {
    style: 'currency',
    currency: 'MXN',
    maximumSignificantDigits: 3
  })
  return formatter.format(value)
}
```

2021-07-09 20:44 UTC, devCharles approved these changes
Antes de dar Merge
@arianaomi Podrías agregar las variables de entorno necesaria al proyecto del API en vercel?

2021-07-16 08:02 UTC, merged