Sirena
kodemia/api.kodemia.mx pull request #43
Opened 2021-07-21 01:15 UTC by arianaomi

- Add endpoint

2021-07-21 02:34 UTC, rrortegaa approved these changes

2021-07-21 05:10 UTC, devCharles requested changes

2021-07-21 05:10 UTC, devCharles commented on src/lib/sirena.js
> +  if (response.status) {
Por que la condición de este if es sobre el status? 
Este if se va a ejecutar en cada llamada sin importar si el status es 200 o 500 o 400 o lo que sea

2021-07-21 05:41 UTC, arianaomi commented on src/lib/sirena.js
> +  if (response.status) {
D: le habia puesto  >= 400,  se me fue

2021-07-21 05:43 UTC, arianaomi commented on src/routes/sirena.js
> +  console.log(ctx.request.body)
ya se los borre :) en el ultimo que subi

2021-07-21 05:43 UTC, arianaomi commented on src/routes/sirena.js
> +  console.log('Response', response)
borrado :)

2021-07-21 05:43 UTC, arianaomi commented on src/usecases/sirena.js
> +}
va que va

2021-07-21 05:45 UTC, arianaomi commented on src/lib/sirena.js
> +  if (response.status) {
D: lo borre por error, tenia >= 400 se lo pongo

2021-07-21 05:47 UTC, arianaomi commented on src/lib/sirena.js
> +    {
va que va

2021-07-21 05:50 UTC, arianaomi commented on src/routes/sirena.js
> +router.post('/send-message', async ctx => {
que nombre propones ?  (send-first-message start-conversation ) ¿?

2021-07-21 05:50 UTC, arianaomi commented on src/usecases/sirena.js
> +async function sendTemplate (email) {
creo que aqui si podria ser sendFirstMessage, como ves?

2021-07-21 06:01 UTC, devCharles commented on src/routes/sirena.js
> +router.post('/send-message', async ctx => {
Yo pondría `/messages/first` 
Idealmente las rutas no deberían llevar verbos y recuerda que el formato según REST es `recurso/identificador`
En este caso nuestro recurso son los mensajes disponibles y el identificador es `first`

2021-07-21 06:01 UTC, devCharles commented on src/usecases/sirena.js
> +async function sendTemplate (email) {
Andale, ese esta mejor

2021-07-22 10:18 UTC, devCharles approved these changes
Yeah! quedó muy bien! 🎉 

Ya solo agrega la linea al final del `.env.example` porfa y demosle merge

2021-07-22 10:18 UTC, devCharles commented on .env.example
> +SIRENA_API_HOST=""
Puedes ponerle una linea en blanco al final de este archivo porfa?

2021-07-22 23:31 UTC, arianaomi commented on .env.example
> +SIRENA_API_HOST=""
okis

2021-07-22 23:37 UTC, merged