Mobile
kodemia/api.kodemia.mx pull request #53
Opened 2021-10-01 05:13 UTC by arianaomi

- add mobile endpoint

2021-10-04 18:05 UTC, devCharles requested changes

2021-10-04 18:05 UTC, devCharles commented on src/routes/active-campaign/apply.js
> +  const dealInList = await ac.lists.subscribeContact(contact.id, course)
Hay que verificar con patsy la lista a la que se van a a gregar estos contactos, y agregar los 2 cursos de mobile al json de configuración

2021-10-04 18:08 UTC, arianaomi commented on src/routes/active-campaign/apply.js
> +  const dealInList = await ac.lists.subscribeContact(contact.id, course)
Le pregunte a Pats a que lista se deben agregar y me dijo que a BJL_2021 porque es la que tiene las automatizaciones

2021-10-04 18:10 UTC, arianaomi commented on src/routes/active-campaign/apply.js
> +    course = 'javascript-live',
es vdd, por defecto seria iOS o android ?

2021-10-04 18:12 UTC, devCharles commented on src/routes/active-campaign/apply.js
> +  const dealInList = await ac.lists.subscribeContact(contact.id, course)
va, entonces solo hay que agregar los programas al json con el mismo id de lista

2021-10-05 20:18 UTC, devCharles approved these changes

2021-10-05 21:01 UTC, merged