Deactivation reason
kodemia/api.kodemia.mx pull request #90
Opened 2022-05-04 00:55 UTC by arianaomi

- Updated the koders model
- updated the endpoint to accept the deactivation reason

![image](https://user-images.githubusercontent.com/14032235/166609909-9c196c92-d167-43f6-b342-3304f62ec31c.png)

2022-05-04 02:53 UTC, devCharles requested changes

2022-05-04 02:53 UTC, devCharles commented on src/usecases/koder.js
> +    throw createError(401, `Koder is not active because ${koder.deactivationReason}`)
Que pasa cuando no hay una razon de desactivación? por que todos los que estan ahorita en la dn no tienen una razon de desactivación

2022-05-04 02:53 UTC, devCharles commented on src/usecases/koder.js
> +    .findOneAndUpdate({ email }, { isActive: false, deactivationReason, password: 'disabled' })
Puedes quitar el password de esta actualización porfa? para que no se les quite el password, solo se marque como desactiado

2022-05-04 02:53 UTC, devCharles commented on src/lib/db.js
> +const DB_HOST = process.env.DB_HOST || ''
Amtes de subir esto temdremos que declarar la variable de entorno necesaria en Vercel

2022-05-04 02:53 UTC, devCharles commented on src/models/koder.js
> +  deactivationReason: {
podemos poner una funcion `required` aqui porfa? para que este campo sea requerido si el `isActive` es `false`

2022-05-04 05:38 UTC, devCharles requested changes

2022-05-04 05:38 UTC, devCharles commented on src/models/koder.js
> +    required: () => !!this.isActive
Aqui deberia ser required cuando isActive s false no true
```suggestion
    required: () => !this.isActive
```

2022-05-04 05:38 UTC, devCharles commented on src/routes/koders.js
> +  const deactivatePromises = koders.map(({ email, deactivationReason }) => koder.deactivateByEmail(email, deactivationReason))
De donde sale `deactivationReason ` ? no veo que este declarado en nigún lugar

2022-05-05 02:06 UTC, arianaomi commented on src/routes/koders.js
> +  const deactivatePromises = koders.map(({ email, deactivationReason }) => koder.deactivateByEmail(email, deactivationReason))
![image](https://user-images.githubusercontent.com/14032235/166854228-692ea867-36b0-4031-b7a2-9adbbec90414.png)


Ahora el payload seria asi

2022-05-05 02:07 UTC, arianaomi commented on src/models/koder.js
> +    required: () => !!this.isActive
Lo puse directamente igual a false ya que si lo ponia asi ! me segui diciendo que era requerido

2022-05-05 02:43 UTC, devCharles commented on src/routes/koders.js
> +  const deactivatePromises = koders.map(({ email, deactivationReason }) => koder.deactivateByEmail(email, deactivationReason))
ya ya vi, es que esta confusa la deconstrucción

2022-05-05 02:44 UTC, devCharles approved these changes

2022-05-05 03:00 UTC, arianaomi commented on src/routes/koders.js
> +  const deactivatePromises = koders.map(({ email, deactivationReason }) => koder.deactivateByEmail(email, deactivationReason))
crees que estaria mas legible koder.email y koder.deactivationReason  ?
@devCharles

2022-05-05 06:58 UTC, devCharles commented on src/routes/koders.js
> +  const deactivatePromises = koders.map(({ email, deactivationReason }) => koder.deactivateByEmail(email, deactivationReason))
@arianaomi Sip, definitivamente

2022-05-05 08:30 UTC, rrortegaa approved these changes

2022-05-06 02:09 UTC, devCharles approved these changes
Demosle merge a esto 🔥 
Buen trabajo @arianaomi  😄 , gracias por el refactor

2022-05-06 02:23 UTC, merged